export class User {
	id: number;
	email : string;
	name : string;
	organization : string;
}


export class SARUser {
	id: number;
	email : string;
	name : string;
	organization : string;
	isAvailable : boolean;
	isTrackable : boolean;
}

export class SARAdmin {
	id: number;
	email: string;
	missions : Mission[];
}

export class Mission {
	id: number;
	isActive : boolean;
	isEmergency : boolean;
	title : string;
	description: string;
	dateStart : Date;
	dateEnd : Date;
	alarms : Alarm[];
	meetingPoint : string;
	creator : SARAdmin;
	expences : Expence[];
}

export class Alarm {
	id : number;
	date : number;
	message : string;
	mission : Mission;
	// Persons to be alarmed
	persons : SARUser[];
	alarmResponses : AlarmResponse[];
}


export class AlarmResponse {
	alarm : Alarm;
	person : SARUser;
	response : boolean;
	date : number;  // Autogenerated time of response
	comment : string;

	// If user has tracking enabled
	trackings : Tracking[];
}

export class Tracking {
	alarmResponse : AlarmResponse;
	positionLat : string;
	positionLong : string;
	date : number;

}


export class Expence {
	id: number;
	title : string;
	description: string;
	amount : number;
	mission : Mission;
	person : SARUser;
}