export class User {
	id: number;
	email: string;
	name: string;
	organization: string;
}


export class SARUser {

	constructor(
		public id: number,
		public hasApp: boolean,
		public isAdmin: boolean,
		public email: string,
		public phone: number,
		public name: string,
		public organization: string,
		public isAvailable: boolean,
		public isTrackable: boolean
	) { }

}



export class Mission {
	constructor(
		public id: number,
		public isActive: boolean,
		public isEmergency: boolean,
		public title: string,
		public description: string,
		public dateStart: Date,
		public dateEnd: Date,
		public alarms: Alarm[],
		public meetingPoint: string, // geolocation { lat, lng }
		public meetingPointNicename: string, // converted geolocation to nicename
		public creator: SARUser,
		public expences: Expence[]
	) { }

}


export class Alarm {
	id: number;

	// datestamp at creation
	date: Date;


	message: string;
	mission: Mission;

	// Persons to be alarmed
	persons: SARUser[];
	alarmResponses: AlarmResponse[];
}


export class AlarmResponse {
	alarm: Alarm;
	person: SARUser;
	response: boolean;
	date: number;  // Autogenerated time of response
	comment: string;

	// If user has tracking enabled
	trackings: Tracking[];
}

export class Tracking {
	alarmResponse: AlarmResponse;
	positionLat: string;
	positionLong: string;
	date: number;

}


export class Expence {
	id: number;
	title: string;
	description: string;
	amount: number;
	mission: Mission;
	person: SARUser;
}